### PR TITLE
Allow insecure connection

### PR DESCRIPTION
**Pull request by thomasjohansen**
Allow insecure HTTPS connections

### CODE REVIEW

**Comment by vitalif** [comment]
Thanks. But I have a question: did you check that mounting works with insecure S3 i.e. that geesefs doesn't complain about the certificate too?

**Comment by thomasjohansen** [comment]
You are right. There's an issue with GeeseFS as well. I gave up!

**Comment by vitalif** [comment]
Why did you give up, you just need to patch it too :))

**Comment by thomasjohansen** [comment]
I tried to patch it, but never got it to work as the package is using the default http transport. As I understand it, it would require to patch all requests - not sure that's a good idea?

**Comment by pasztorl** [comment]
Why not allow to mount the ca certificate in the helm templates?

**Pull request closed without merging**
