### PR TITLE
sync

### PR DESCRIPTION
**Pull request by bluebossa63**

### CODE REVIEW

**Comment by bluebossa63** [comment]
sorry, wrong repo

**Comment by bluebossa63** [comment]
Hey guys, please checkout my upgrade to the latest versions. I had some findings by scanning the container for vulnerabilities.

I am working on a refreshed version for geesefs as well.

**Comment by vitalif** [comment]
Hi. Sorry but my reaction to this is... WTF?)))
I definitely won't merge it as is.
Please split the PR into a series of **small** and **meaningful** improvements. A negative example is variable or class renames without actual need :)

**Comment by bluebossa63** [comment]
OK, I close it. It was just an offer to update an outdated container.

**Comment by vitalif** [comment]
You didn't even describe what you were fixing :)))

**Comment by bluebossa63** [comment]
yes: upgrade to the latest versions because your image is full of vulnerabilities.

Listen, this was just an offer to backport it.

**Pull request closed without merging**
